### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by gaustin** [AntonFagerberg/rackla#16]
Hi, I'm new to Elixir so I may be poking up the wrong tree here.

I need to make requests to services over basic auth. I understand that Hackney handles outbound requests, but I haven't figured out how to pass basic auth to it through Rackla.

Any ideas?

Thanks in advance.

**Comment by AntonFagerberg** [comment]
Hi @gaustin,

You can do it in two different ways.

Either by sending the username and password in the headers:

```elixir
  get "/auth-example" do
    url = "http://some-url.com"
    headers = %{"Authorization" => "Basic #{Base.encode64("username:password")}"}
    
    %Rackla.Request{url: url, headers: headers}
    |> request
    |> response
  end
```

Or by directly adding them to the URL:

```elixir
get "/auth-example" do
  "http://username:password@some-url.com"
  |> request
  |> response
end
```

Hope it helps! 😄

**Comment by gaustin** [comment]
That works. Thanks!

It looked like maybe Hackney had a facility to generate the basic auth header automatically, but this is easy enough.
