### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by JustMikey** [AntonFagerberg/rackla#18]
Hi, I was wondering if you would consider adding an option for using the proxy for requests?

And thank you for the package, it's great :)

**Comment by AntonFagerberg** [comment]
Thanks a lot for the kind words!

I'm not 100% sure of what you mean by using the proxy for request? If you mean that Rackla should be able to proxy incoming requests to another server then I think that would be a great idea which I'll definitely look in to.

After reading #17, I think it would be a good start to be able to convert an incoming "Plug request" to a "Rackla request". If we then just modify (at least) the url, I think you could use that functionality to proxy requests easily.

**Comment by JustMikey** [comment]
Like, take for example a situation when you have an API but it's behind the firewall so you have to make the outgoing requests go through that firewall so the proxy option would be a good thing to have. Hackney seems to support this option so it should be easy enough to do.

**Comment by AntonFagerberg** [comment]
Aha, now I understand what you mean and yes, I can absolutely add this to Rackla. Since it's supported by Hackney it's a fairly trivial change.

I'll try to add it over the weekend!

**Comment by JustMikey** [comment]
That would be great, thank you very much :)

**Comment by AntonFagerberg** [comment]
I've added support for proxies in develop now. I need to do some more testing and I have one more thing I want to add before I make a proper release - but if you wish to try it out before the release, just clone the latest develop!

Example usages:
```elixir
%Rackla.Request{url: "http://api.ipify.org", options: %{proxy: %Rackla.Proxy{type: :socks5, host: "localhost", port: 8080}}} |> Rackla.request |> Rackla.collect
```

```elixir
"http://api.ipify.org" |> Rackla.request(proxy: %Rackla.Proxy{type: :socks5, host: "localhost", port: 8080}) |> Rackla.collect
```

**Comment by JustMikey** [comment]
Thank you very much for your work. I will try it after this weekend. Also I wanted to point out that it may make sense to add a way to use authentication for the proxy, if it's is required. I believe hackney has the `proxy_auth` option for that.

**Comment by AntonFagerberg** [comment]
Username and password is already present in the Rackla.Proxy struct but I see now that it is only used for socks5 and not http tunnelling (which uses `proxy_auth`). I'll add support for that also.

**Comment by JustMikey** [comment]
Yeah, that would be great :)

**Comment by AntonFagerberg** [comment]
I just pushed a new commit to develop, username and password should work on both socks5 and HTTP tunnels (connect).

It's not tested though so it would be great if you could report back if everything works as expected when you try it out !

**Comment by JustMikey** [comment]
Sure, will do :) Do you have any idea of how it could be covered with tests?

**Comment by AntonFagerberg** [comment]
No, that's a tough one! I'm guessing it's hard to mock and actually
launching two different proxies just for unit testing feels like a heavy
dependency to include. Maybe Hackney have some tests that can be
repurposed?

--
Anton Fagerberg


On Sat, Sep 3, 2016, at 07:22 PM, Michael wrote:
> Sure, will do :) Do you have any idea of how it could be covered
> with tests?
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/AntonFagerberg/rackla/issues/18#issuecomment-244558774

**Comment by JustMikey** [comment]
Yeah I agree, I am not sure how to test it as well. I will look into it tomorrow.

**Comment by JustMikey** [comment]
Why do you transform host to an atom [here](https://github.com/AntonFagerberg/rackla/blob/develop/lib/rackla/rackla.ex#L79) ?

**Comment by AntonFagerberg** [comment]
That's because the Elixir string didn't work (and that's because Erlang and Elixir represents strings differently but I didn't think about that when I wrote the). Using `to_charlist` is probably a better approach or do you have another suggestion?

**Comment by JustMikey** [comment]
Well, converting it to an atom may be dangerous because GC doesn't collect those so it may lead to the memory leaks if somebody uses it dynamically. I am not sure... If hackney accepts a binary, then elixir strings should work since they are binaries, but apparently hackney doesn't, so then probably a char list should work, yeah.

**Comment by AntonFagerberg** [comment]
It's true that they aren'g GCed but I reasoned that using a lot of dynamic proxies seemed like a very unlikely scenario :) Nevertheless, it's better to avoid them if possible.  

I will double check the issue I had with Elixir strings to see what it was about.

I did the testing using a SOCKS5 proxy, are you that as well?

**Comment by JustMikey** [comment]
Well, I tried it with HTTP proxy and it did not work, but then I removed those strings to atoms transformations in the proxy settings and it did work.

**Comment by AntonFagerberg** [comment]
Ok, I'll try both proxy types in a couple of hours and sort it all out. Thanks for the update!

**Comment by JustMikey** [comment]
Thank you!

**Comment by AntonFagerberg** [comment]
Release as part of version 1.1.0!

**Comment by JustMikey** [comment]
Thank you so much for the package and your time :)
