### ISSUE TITLE
Auto-reload during development

### ISSUE THREAD

**Issue by AntonFagerberg** [AntonFagerberg/rackla#4]
Auto-reloading would be a nice feature. Investigate how this has been implemented in Phoenix.

**Comment by pap** [comment]
Any objection in using something like [remix](https://hex.pm/packages/remix) ?

**Comment by AntonFagerberg** [comment]
@pap Thanks for the suggestion! The coming week(s) are very busy for me since I'm moving but I will take a look at this as soon as I can :)

**Comment by pap** [comment]
@AntonFagerberg Just wanted to know if you had any other thing in mind.  I'll make a PR for it, probably tomorrow. BTW reading your thesis. Good stuff !

**Comment by AntonFagerberg** [comment]
@pap Awesome, thanks a lot!

**Comment by pap** [comment]
Nope. Thank you !

**Comment by AntonFagerberg** [comment]
Fixed in #14
